version = "3.8.3"
runner.dialect = scala3
maxColumn = 150
lineEndings = unix
indent.main = 2
indent.callSite = 2
indent.defnSite = 2
project.git = true
rewrite.rules = [RedundantBraces, RedundantParens, SortImports, AvoidInfix]