package com.sslproxy.schema.cli

import cats.effect.ExitCode
import cats.effect.IO
import com.sslproxy.schema.TestSqlSupport
import munit.FunSuite

import java.nio.file.Files

class CommandsSuite extends FunSuite with TestSqlSupport:
  test("validate does not require database connection settings") {
    val exitCode = withSqlDir { sqlDir =>
      Commands.run(config(sqlDir), CliCommand.Validate)
    }

    assertEquals(exitCode, ExitCode.Success)
  }

  test("dry-run apply does not require database connection settings") {
    val exitCode = withSqlDir { sqlDir =>
      Commands.run(config(sqlDir).copy(dryRun = true), CliCommand.Apply)
    }

    assertEquals(exitCode, ExitCode.Success)
  }

  test("generate-baseline writes generated artifact without database connection settings") {
    val exitCode = withSqlDir { sqlDir =>
      val output = sqlDir.resolve("_generated_baseline.sql")
      for
        code <- Commands.run(config(sqlDir), CliCommand.GenerateBaseline)
        _ <- IO.blocking {
          assert(Files.isRegularFile(output))
          val generated = Files.readString(output)
          assert(generated.contains("Generated by schema-migrator. Do not edit by hand."))
          assert(generated.contains("-- source: tables/001_devices.sql"))
          assert(generated.contains("create table if not exists public.devices"))
        }
      yield code
    }

    assertEquals(exitCode, ExitCode.Success)
  }
