package com.sslproxy.schema.discovery

import cats.effect.IO
import com.sslproxy.schema.config.DbKind

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Path}

object BaselineGenerator:
  def write(sqlDir: Path, dbKind: DbKind, files: List[SqlFile]): IO[Path] =
    IO.blocking {
      val output = SqlLayout.generatedBaselinePath(sqlDir, dbKind)
      Files.createDirectories(output.getParent)
      Files.writeString(output, render(dbKind, files), StandardCharsets.UTF_8)
      output
    }

  def render(dbKind: DbKind, files: List[SqlFile]): String =
    val body = files
      .map { file =>
        val sql = file.readString.stripTrailing()
        s"""-- ============================================================================
           |-- source: ${file.relativePath}
           |-- ============================================================================
           |$sql
           |""".stripMargin
      }
      .mkString("\n")

    s"""-- Generated by schema-migrator. Do not edit by hand.
       |-- Engine: ${SqlLayout.engineName(dbKind)}
       |-- Source of truth: split SQL files listed by manifest.yaml
       |
       |$body""".stripMargin
